############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "About"
url = "/about"
weight = 2

[[main]]
name = "Blogs"
url = "/blog"
weight = 3

[[main]]
name = "Categories"
url = "/categories"
weight = 4

[[main]]
name = "Authors"
url = "/authors"
weight = 5

# Parent Dropdown
[[main]]
name = "Pages"
weight = 6

# Child Item inside Pages
[[main]]
parent = "Pages"
name = "Elements"
url = "/elements"


# footer menu
[[footer]]
name = "About"
url = "/about"
weight = 1

[[footer]]
name = "Elements"
url = "/elements"
weight = 2

[[footer]]
name = "Privacy Policy"
url = "/privacy-policy"
weight = 3